######################################################################
# Automatically generated by qmake (2.01a) pon. kwi 7 18:59:42 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
DESTDIR= ./build/

# Input
HEADERS += Queue.h Queue_gui.h
FORMS += Queue_gui.ui
SOURCES += Main.cc Queue.cc Queue_gui.cc Stts.cc Distributions.cc
